
server:
  port: 5000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/schedule?useLegacyDatetimeCode=false
    username: root

    password: root
  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
