
server:
  port: 5000
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/schedule?useLegacyDatetimeCode=false
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: false
    show-sql: true
  jackson:
    serialization.fail-on-empty-beans: false
